# Variables de entorno requeridas en .env raíz:
# DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASSWORD
# REDIS_HOST, REDIS_PORT
# APP_ENV, APP_SECRET, ADMIN_PASSWORD_HASH
# MAILER_DSN, NOTIFICATION_TO_EMAIL, NOTIFICATION_FROM_EMAIL
# VITE_API_BASE

services:
  electri-backend-php:
    build:
      context: ./backend
      target: dev
    container_name: electri-backend-php
    env_file: .env
    environment:
      DATABASE_URL: "pgsql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?serverVersion=16&charset=utf8"
      REDIS_URL: "redis://${REDIS_HOST}:${REDIS_PORT}"
    restart: unless-stopped  
    volumes:
      - ./backend:/var/www/html
    networks:
      - shared-network

  electri-frontend:
    build:
      context: ./frontend
      target: prod-stage  # Apunta a la segunda etapa del Dockerfile
    container_name: electri-frontend
    restart: unless-stopped
    # Ya NO necesitamos el comando "npm run dev"
    # Ya NO necesitamos mapear "node_modules"
    networks:
      - shared-network
    volumes:
      - ./frontend:/app # Opcional en prod, pero útil para persistencia
      
networks:
  shared-network:
    name: shared-network
    external: true
