services:
  electri-backend-php:
    build:
      context: ./backend
      target: prod
    container_name: electri-backend-php
    env_file: .env
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      DATABASE_URL: "pgsql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?serverVersion=16&charset=utf8"
      REDIS_URL: "redis://${REDIS_HOST}:${REDIS_PORT}"
    restart: unless-stopped
    networks:
      - shared-network

  electri-frontend:
    build:
      context: ./frontend
      target: prod
    container_name: electri-frontend
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
    name: shared-network
    external: true
